NEWS = [
    {
        "url": "https://blog.betrybe.com/novidades/noticia_5.htm",
        "title": "noticia_5",
        "timestamp": "23/11/2020",
        "writer": "Escritor_5",
        "reading_time": 1,
        "summary": "Sumario da noticia_5",
        "category": "Categoria_0",
    },
    {
        "url": "https://blog.betrybe.com/novidades/noticia_6.htm",
        "title": "noticia_6",
        "timestamp": "23/11/2020",
        "writer": "Escritor_6",
        "reading_time": 1,
        "summary": "Sumario da noticia_6",
        "category": "Novidades",
    },
    {
        "url": "https://blog.betrybe.com/novidades/noticia_7.htm",
        "title": "noticia_7",
        "timestamp": "23/11/2020",
        "writer": "Escritor_7",
        "reading_time": 7,
        "summary": "Sumario da noticia_1",
        "category": "Categoria_7",
    },
    {
        "url": "https://blog.betrybe.com/novidades/noticia_8.htm",
        "title": "noticia_8",
        "timestamp": "23/11/2020",
        "writer": "Escritor_7",
        "reading_time": 8,
        "summary": "Sumario da noticia_8",
        "category": "Categoria_7",
    },
    {
        "url": "https://blog.betrybe.com/novidades/noticia_9.htm",
        "title": "noticia_9",
        "timestamp": "23/11/2020",
        "writer": "Escritor_7",
        "reading_time": 5,
        "summary": "Sumario da noticia_9",
        "category": "Categoria_9",
    },
]
